### ISSUE TITLE
The scoreboard does not disappear after the game is over

### ISSUE THREAD

**Issue by JuChanMin** [lt-name/HotPotato_Nukkit#12]
HotPotato's ScoreBoard does not disappear after moving to the World after the game is over :c

**Comment by lt-name** [comment]
Can you provide detailed version information?
For example: 1.0.0 git-XXXXX

**Comment by JuChanMin** [comment]
I'm sorry, I forgot to send important information Xd

I used 1.0.2-SnapShot git-553a8a0 ([HotPotato](https://github.com/lt-name/HotPotato_Nukkit/actions/runs/238831693))
and I used PowerNukkit-1.4.0.0-SnapShot ([PowerNukkit](https://github.com/PowerNukkit/PowerNukkit/actions/runs/264299427))

**Comment by lt-name** [comment]
Maybe it’s a problem with the Tips plugin, you can try to delete the configuration of the Tips plugin
Hotpotato 1.0.2 version does not depend on Tips, You only need to install the ScoreboardAPI

**Comment by JuChanMin** [comment]
I don't use the Tips plugin, I run MurderMystery and HotPotato together with ScoreBoardAPI..
I will test again with the recently uploaded 85fbf62. 
Thanks for answering! :)

**Comment by JuChanMin** [comment]
It looks like your plugin optimization has had an impact! :D
Now, when the game is over, ScoreBoard is removed normally.
Thanks for fixing it! :3
