### ISSUE TITLE
增加在游戏房间中使用命令的白名单

### ISSUE THREAD

**Issue by gougocoffee** [lt-name/HotPotato_Nukkit#13]
![{3ZRO~GV86YT 4A`FKUDB P](https://user-images.githubusercontent.com/49330438/182021230-af315a93-1e48-429f-853a-7963a12d82ee.png)
比如 hub lobby 这些命令

**Comment by lt-name** [comment]
已添加，请参考 https://github.com/lt-name/HotPotato_Nukkit/blob/master/src/main/resources/config.yml 手动补全配置文件
