### ISSUE TITLE
[BUG]/hub /lobby指令无法退出房间

### ISSUE THREAD

**Issue by gougocoffee** [lt-name/HotPotato_Nukkit#14]
![J2OD)5N(OW3HKT5ZNM5@Y1E](https://user-images.githubusercontent.com/49330438/182024794-a2d3fbe4-acd7-456c-ae9e-549940f636ef.png)
![S}1NGB P8KWHP4WXO2(1IPY](https://user-images.githubusercontent.com/49330438/182024800-983cf4af-88da-4223-8132-a61e9e98a3ba.png)
输入其他插件的/hub，/lobby无法退出房间

**Comment by gougocoffee** [comment]
会显示 退出房间请使用命令

**Comment by lt-name** [comment]
已修复
