### ISSUE TITLE
[BUG]进入房间大厅物品没有清除

### ISSUE THREAD

**Issue by gougocoffee** [lt-name/HotPotato_Nukkit#17]
进入房间大厅物品没有清除

“这些物品是锁定的”

**Comment by irapda** [comment]
![image](https://user-images.githubusercontent.com/49330438/182025597-9261fe5d-8627-4412-a58b-769dce6bc8e2.png)

**Comment by irapda** [comment]
如果这些物品是黄色的锁也清理不掉

**Comment by gougocoffee** [comment]
菜单插件的问题
