### ISSUE TITLE
[BUG]玩家逃跑，游戏无法结束

### ISSUE THREAD

**Issue by gougocoffee** [lt-name/HotPotato_Nukkit#19]
![3$O 2O)F)ZJ@}8WGN5~G40B](https://user-images.githubusercontent.com/49330438/182066463-230d8983-3042-4ac5-9c18-40d001154e4e.png)
当游戏内还剩下最后两个玩家
![OE%{TZA~{HH){XU5WOX_GZX](https://user-images.githubusercontent.com/49330438/182066522-526ddca9-b989-40db-b2d6-ff383a5ec5a0.png)
但是另一位玩家逃跑了，山芋丢给谁？导致游戏无法结束，控制台报错如下：
![~)3@1} K$X(QVM1N EC)3I](https://user-images.githubusercontent.com/49330438/182066646-4534bbc8-c1b8-4929-92a2-9dcac83b6657.png)

**Comment by lt-name** [comment]
已修复
