### ISSUE TITLE
退出房间执行命令功能失效 

### ISSUE THREAD

**Issue by szzz666** [lt-name/HotPotato_Nukkit#23]
Nukkit PM1E 1.19.80.2964服务端
是在你的构建站下载的
![image](https://github.com/lt-name/HotPotato_Nukkit/assets/60167194/1d840529-b802-4841-a0b2-98dce8562177)
这个
退出房间执行命令功能失效
没有报错
HotPotato_Nukkit和CrystalWars插件都有这个问题

**Comment by lt-name** [comment]
已添加退出房间执行命令功能

**Comment by szzz666** [comment]
ok

**Comment by szzz666** [comment]
谢谢
