### ISSUE TITLE
Cant start plugin

### ISSUE THREAD

**Issue by JuChanMin** [lt-name/HotPotato_Nukkit#8]
"Unknown dependency" An error is generated. :c

I used NukkitX and PowerNukkit

**Comment by lt-name** [comment]
Please install this plugin：
https://github.com/lt-name/HotPotato_Nukkit/blob/master/lib/Tips_v1.6.3.jar
Detailed introduction：
https://www.mcbbs.net/thread-939814-1-2.html
(Google Translate)

**Comment by JuChanMin** [comment]
I put Tip and Economy in my server, and I fixed bugs!
Thank you :3
